// Generated by CoffeeScript 1.4.0
var check, check_ignore, delay_time, disappear_time, feed_api_url, last_time, main, notify, proc, user_api_url,
  __slice = [].slice,
  _this = this;

feed_api_url = "https://www.yammer.com/api/v1/messages/my_feed.json";

user_api_url = "https://www.yammer.com/api/v1/users/";

delay_time = 60 * 3;

last_time = 0;

disappear_time = 5;

check = function() {
  if (localStorage.ls_update_interval != null) {
    delay_time = 60 * localStorage.ls_update_interval;
  }
  if (localStorage.ls_notification_interval != null) {
    disappear_time = localStorage.ls_notification_interval;
  }
  main();
  return setTimeout(check, delay_time * 1000);
};

main = function() {
  return jQuery(function() {
    var _this = this;
    return $.getJSON(feed_api_url, function(response) {
      var items;
      items = response.messages;
      return proc(items);
    });
  });
};

proc = function(items) {
  var head, new_date, tail, user_id;
  head = items[0], tail = 2 <= items.length ? __slice.call(items, 1) : [];
  user_id = head.sender_id;
  new_date = Date.parse(head.created_at);
  if (new_date > last_time) {
    return jQuery(function() {
      var _this = this;
      return $.getJSON(user_api_url + user_id + ".json", function(response) {
        var fullname, messeage, type, web_url;
        fullname = response.full_name;
        localStorage.ls_user_name = fullname;
        localStorage.ls_mugshot_url = response.mugshot_url;
        if (check_ignore(fullname)) {
          web_url = head.web_url;
          messeage = head.body.parsed;
          type = head.message_type;
          localStorage.ls_web_url = web_url;
          localStorage.ls_message = messeage;
          localStorage.ls_type = type;
          last_time = new_date;
          return notify();
        } else {
          return proc(tail);
        }
      });
    });
  }
};

notify = function() {
  var notifications;
  notifications = webkitNotifications.createHTMLNotification(chrome.extension.getURL("notification.html"));
  notifications.addEventListener("click", function() {
    var target_url;
    notifications.cancel();
    if (localStorage.ls_notification_link === "page") {
      target_url = localStorage.ls_web_url;
      return window.open(target_url);
    } else {
      return window.open("https://www.yammer.com");
    }
  });
  notifications.show();
  if (localStorage.ls_notification_interval !== "none") {
    return setTimeout((function() {
      return notifications.cancel();
    }), disappear_time * 1000);
  }
};

$(function() {
  return check();
});

check_ignore = function(fullname) {
  var all_ignore;
  all_ignore = JSON.parse(localStorage.ls_all_ignore);
  if (all_ignore.fullnames.indexOf(fullname) !== -1) {
    return false;
  } else {
    return true;
  }
};

chrome.browserAction.onClicked.addListener(function(tab) {
  return chrome.tabs.create({
    'url': 'https://www.yammer.com/'
  }, (function(tab) {}));
});
