// Generated by CoffeeScript 1.4.0
var save_ignore, update_ignore_list;

$(function() {
  var all_ignore;
  if (localStorage.ls_update_interval != null) {
    $("#update_interval").val(localStorage.ls_update_interval);
  }
  if (localStorage.ls_notification_interval != null) {
    $("#notification_interval").val(localStorage.ls_notification_interval);
  }
  if (localStorage.ls_notification_link != null) {
    $("#notification_link").val(localStorage.ls_notification_link);
  }
  all_ignore = JSON.parse(localStorage.ls_ignore_email);
  update_ignore_list(all_ignore);
  $("#save_button").click(function() {
    var notification_interval, notification_link, update_interval;
    update_interval = $("#update_interval").val();
    notification_interval = $("#notification_interval").val();
    notification_link = $("#notification_link").val();
    localStorage.ls_update_interval = update_interval;
    localStorage.ls_notification_interval = notification_interval;
    localStorage.ls_notification_link = notification_link;
    return alert("save");
  });
  $("#save_ignore_button").click(function() {
    return save_ignore();
  });
  return $("#clear_ignore_button").click(function() {
    localStorage.ls_ignore_email = JSON.stringify({
      emails: []
    });
    return update_ignore_list(null);
  });
});

save_ignore = function() {
  var all_ignore, ignore_email;
  ignore_email = $("#ignore_email").val();
  if (ignore_email.length !== 0) {
    if (localStorage.ls_ignore_email != null) {
      all_ignore = JSON.parse(localStorage.ls_ignore_email);
      all_ignore.emails.push(ignore_email);
      localStorage.ls_ignore_email = JSON.stringify(all_ignore);
    }
    update_ignore_list(all_ignore);
    return $("#ignore_email").val("");
  }
};

update_ignore_list = function(all_ignore) {
  var ignore_email, _i, _len, _ref, _results;
  $("#ignore_list").empty();
  if (all_ignore != null) {
    _ref = all_ignore.emails;
    _results = [];
    for (_i = 0, _len = _ref.length; _i < _len; _i++) {
      ignore_email = _ref[_i];
      _results.push($("#ignore_list").append("<li>" + ignore_email + "</li>"));
    }
    return _results;
  }
};
