// Generated by CoffeeScript 1.4.0
(function() {

  $(function() {
    if (localStorage.ls_update_interval != null) {
      $("#update_interval").val(localStorage.ls_update_interval);
    }
    if (localStorage.ls_notification_interval != null) {
      $("#notification_interval").val(localStorage.ls_notification_interval);
    }
    return $("#save_button").click(function() {
      var notification_interval, update_interval;
      update_interval = $("#update_interval").val();
      notification_interval = $("#notification_interval").val();
      localStorage.ls_update_interval = update_interval;
      localStorage.ls_notification_interval = notification_interval;
      return alert("save");
    });
  });

}).call(this);
