// Generated by CoffeeScript 1.4.0
var save_ignore, search_by_email_api, update_ignore_list,
  __slice = [].slice;

search_by_email_api = "https://www.yammer.com/api/v1/users/by_email.json?email=";

$(function() {
  var all_ignore;
  if (localStorage.ls_update_interval != null) {
    $("#update_interval").val(localStorage.ls_update_interval);
  }
  if (localStorage.ls_notification_interval != null) {
    $("#notification_interval").val(localStorage.ls_notification_interval);
  }
  if (localStorage.ls_notification_link != null) {
    $("#notification_link").val(localStorage.ls_notification_link);
  }
  if (localStorage.ls_all_ignore != null) {
    all_ignore = JSON.parse(localStorage.ls_all_ignore);
  }
  update_ignore_list(all_ignore);
  $("#save_button").click(function() {
    var notification_interval, notification_link, update_interval;
    update_interval = $("#update_interval").val();
    notification_interval = $("#notification_interval").val();
    notification_link = $("#notification_link").val();
    localStorage.ls_update_interval = update_interval;
    localStorage.ls_notification_interval = notification_interval;
    localStorage.ls_notification_link = notification_link;
    return alert("save");
  });
  $("#save_ignore_button").click(function() {
    return save_ignore();
  });
  return $("#clear_ignore_button").click(function() {
    localStorage.ls_all_ignore = JSON.stringify({
      fullnames: []
    });
    return update_ignore_list(null);
  });
});

save_ignore = function() {
  var ignore_email;
  ignore_email = $("#ignore_email").val();
  if (ignore_email.length !== 0) {
    return jQuery(function() {
      var _this = this;
      return $.getJSON(search_by_email_api + ignore_email, function(response) {
        var all_ignore, fullname, head, tail;
        head = response[0], tail = 2 <= response.length ? __slice.call(response, 1) : [];
        fullname = head.full_name;
        if (localStorage.ls_all_ignore != null) {
          all_ignore = JSON.parse(localStorage.ls_all_ignore);
          all_ignore.fullnames.push(fullname);
        } else {
          all_ignore = {
            fullnames: [fullname]
          };
        }
        localStorage.ls_all_ignore = JSON.stringify(all_ignore);
        update_ignore_list(all_ignore);
        return $("#ignore_email").val("");
      });
    });
  }
};

update_ignore_list = function(all_ignore) {
  var fullname, _i, _len, _ref, _results;
  $("#ignore_list").empty();
  if (all_ignore != null) {
    _ref = all_ignore.fullnames;
    _results = [];
    for (_i = 0, _len = _ref.length; _i < _len; _i++) {
      fullname = _ref[_i];
      _results.push($("#ignore_list").append("<li>" + fullname + "</li>"));
    }
    return _results;
  }
};
