// Generated by CoffeeScript 1.4.0
var check_update, delay_seconds, notify, previous_post_time, process, target_url,
  __slice = [].slice;

delay_seconds = 60 * 5;

target_url = "https://www.yammer.com/api/v1/streams/notifications.json";

previous_post_time = 0;

check_update = function() {
  console.log("check start");
  process();
  return setTimeout(check_update, 1000 * delay_seconds);
};

process = function() {
  console.log("process2");
  return jQuery(function() {
    var _this = this;
    return $.getJSON(target_url, function(response) {
      var head, items, new_date, new_messeage, tail;
      items = response.items;
      head = items[0], tail = 2 <= items.length ? __slice.call(items, 1) : [];
      new_messeage = head.message;
      new_date = Date.parse(head.created_at);
      if (new_date > previous_post_time) {
        previous_post_time = new_date;
        notify(new_messeage);
      }
      return console.log(new_messeage);
    });
  });
};

notify = function(msg) {
  var note;
  note = webkitNotifications.createNotification(null, "New!", msg);
  return note.show();
};

$(function() {
  console.log("check start");
  process();
  return setTimeout(check_update, 1000 * delay_seconds);
});
